# Generated by Django 5.2.5 on 2025-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('img', models.CharField()),
                ('reviews', models.IntegerField()),
                ('content', models.CharField()),
                ('upc', models.CharField()),
                ('producttype', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricetax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.IntegerField()),
                ('reviewscount', models.IntegerField()),
            ],
        ),
    ]
