# Generated by Django 5.2.6 on 2025-11-09 16:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField()),
                ('img', models.URLField()),
                ('reviews', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('content', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reviews_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('writed_at', models.DateField()),
                ('author', models.CharField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
