# Generated by Django 5.2.5 on 2025-08-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ganre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='books.category'),
            preserve_default=False,
        ),
    ]
