# Generated by Django 5.2.5 on 2025-08-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_ganre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ganre',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.category'),
        ),
    ]
