# Generated by Django 5.2.5 on 2025-08-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_ganre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ganre',
            new_name='ganres',
        ),
    ]
