# Generated by Django 5.2.5 on 2025-08-26 17:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_ganre_books_ganres'),
    ]

    operations = [
        migrations.CreateModel(
            name='apikey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateField(default=datetime.date(2025, 12, 12)),
        ),
        migrations.AlterField(
            model_name='books',
            name='ganres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.category'),
        ),
    ]
