# Generated by Django 5.2.5 on 2025-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_apikey_books_date_alter_books_ganres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(),
        ),
    ]
