# Generated by Django 5.2.6 on 2025-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_need_reset',
            field=models.BooleanField(default=False),
        ),
    ]
